// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzdhrskitbnwimzlqadh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6ZGhyc2tpdGJud2ltemxxYWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2OTY5MTEsImV4cCI6MjA3MjI3MjkxMX0.pYVHZVw8rvLzzMKfVR_ibEz_jthf2jT9efqVIzkTcHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});